### PR TITLE
Update challenges to latest Kakoune mappings

### PR DESCRIPTION
**Pull request by arrufat**
## Results with Kakoune v2021.11.08:

- 80 Better
- 17 Same
- 36 Worse
- 2 Fail

## Results with Kakoune 2022.10.31 after modification (they were all failing)

- 80 Better
- 17 Same
- 38 Worse
- 0 Fail

## Detailed results:

| Challenge                                              | Kakoune v2021.11.08  | Kakoune v2022.10.31  |
|--------------------------------------------------------|----------------------|----------------------|
| http://vimgolf.com/challenges/4d1a1c36567bac34a9000002 | OK (34 keys, vim 32) | OK (35 keys, vim 32) |
| http://vimgolf.com/challenges/4d1a34ccfa85f32065000004 | OK (11 keys, vim 13) | OK (12 keys, vim 13) |
| http://vimgolf.com/challenges/4d1a71b5b8cb340932000109 | OK (22 keys, vim 22) | OK (22 keys, vim 22) |
| http://vimgolf.com/challenges/4d1a71c0b8cb34093200010b | OK (37 keys, vim 39) | OK (38 keys, vim 39) |
| http://vimgolf.com/challenges/4d1a790fb8cb3409320001a8 | OK (18 keys, vim 23) | OK (18 keys, vim 23) |
| http://vimgolf.com/challenges/4d1a7a05b8cb3409320001b4 | OK (12 keys, vim 15) | OK (12 keys, vim 15) |
| http://vimgolf.com/challenges/4d1a8bf2b8cb3409320002c4 | OK (12 keys, vim 12) | OK (12 keys, vim 12) |
| http://vimgolf.com/challenges/4d1aaf2fb11838287d000036 | OK (14 keys, vim 12) | OK (14 keys, vim 12) |
| http://vimgolf.com/challenges/4d1ac1800a045132c0000011 | OK (20 keys, vim 22) | OK (20 keys, vim 22) |
| http://vimgolf.com/challenges/4d1b1b97c58eaa2a8a0002fc | OK (42 keys, vim 39) | OK (42 keys, vim 39) |
| http://vimgolf.com/challenges/4d1b4ac3c58eaa2a8a0005c2 | OK (15 keys, vim 14) | OK (15 keys, vim 14) |
| http://vimgolf.com/challenges/4d1cdb0635b40650b8000527 | OK (16 keys, vim 16) | OK (16 keys, vim 16) |
| http://vimgolf.com/challenges/4d1db1b8de2f897c2a00014a | OK (10 keys, vim 11) | OK (10 keys, vim 11) |
| http://vimgolf.com/challenges/4d1e29fda93ce03311000066 | OK (10 keys, vim 12) | OK (10 keys, vim 12) |
| http://vimgolf.com/challenges/4d1e634e509d6e19d8000081 | OK (13 keys, vim 11) | OK (13 keys, vim 11) |
| http://vimgolf.com/challenges/4d2c9d06eda6262e4e00007a | OK (7 keys, vim 18)  | OK (7 keys, vim 18)  |
| http://vimgolf.com/challenges/4d4ab047795d626036000034 | OK (18 keys, vim 17) | OK (18 keys, vim 17) |
| http://vimgolf.com/challenges/4d665abd7d73e02a55000009 | OK (67 keys, vim 67) | OK (67 keys, vim 67) |
| http://vimgolf.com/challenges/4d6f45b938c0aa691b000003 | OK (19 keys, vim 21) | OK (20 keys, vim 21) |
| http://vimgolf.com/challenges/4d716c76919202611400002b | OK (10 keys, vim 13) | OK (10 keys, vim 13) |
| http://vimgolf.com/challenges/4dcd7b572c8e510001000005 | OK (12 keys, vim 15) | OK (12 keys, vim 15) |
| http://vimgolf.com/challenges/4ddbd92898957e0001000016 | OK (10 keys, vim 12) | OK (11 keys, vim 12) |
| http://vimgolf.com/challenges/4e31627b74ab580001000007 | OK (64 keys, vim 65) | OK (64 keys, vim 65) |
| http://vimgolf.com/challenges/4e9edef5cef4c50001000007 | OK (23 keys, vim 23) | OK (23 keys, vim 23) |
| http://vimgolf.com/challenges/4ef209ef78702b0001000019 | OK (10 keys, vim 13) | OK (10 keys, vim 13) |
| http://vimgolf.com/challenges/4f438739f5a8d70001000019 | OK (19 keys, vim 18) | OK (19 keys, vim 18) |
| http://vimgolf.com/challenges/4fbf8e303be58b0001000024 | OK (38 keys, vim 35) | OK (36 keys, vim 35) |
| http://vimgolf.com/challenges/4fc9d767d3a0d4000100000e | OK (8 keys, vim 11)  | OK (8 keys, vim 11)  |
| http://vimgolf.com/challenges/4fca701fd3a0d40001000074 | OK (11 keys, vim 15) | OK (11 keys, vim 15) |
| http://vimgolf.com/challenges/4fcccb70024f950001000026 | OK (9 keys, vim 11)  | OK (9 keys, vim 11)  |
| http://vimgolf.com/challenges/50048db8cdc4060002000004 | FAIL (17 keys, vim 21) | OK (17 keys, vim 21) |
| http://vimgolf.com/challenges/5035e5b3838d9e000200006d | OK (35 keys, vim 32) | OK (35 keys, vim 32) |
| http://vimgolf.com/challenges/504e43017890650002000019 | OK (10 keys, vim 8)  | OK (10 keys, vim 8)  |
| http://vimgolf.com/challenges/50502d985cfbf50002000022 | OK (18 keys, vim 19) | OK (18 keys, vim 19) |
| http://vimgolf.com/challenges/50ad2cb165b8db0002000029 | OK (15 keys, vim 16) | OK (15 keys, vim 16) |
| http://vimgolf.com/challenges/50ae009b65b8db0002000047 | OK (8 keys, vim 7)   | OK (8 keys, vim 7)   |
| http://vimgolf.com/challenges/50b1d7239aad89000200002d | FAIL (24 keys, vim 28) | OK (25 keys, vim 28) |
| http://vimgolf.com/challenges/50bda7a73645b3000200004b | OK (17 keys, vim 16) | OK (18 keys, vim 16) |
| http://vimgolf.com/challenges/50c13afab855760002000049 | OK (14 keys, vim 15) | OK (16 keys, vim 15) |
| http://vimgolf.com/challenges/50c2c246b0544c000200003f | OK (14 keys, vim 14) | OK (14 keys, vim 14) |
| http://vimgolf.com/challenges/50d0c33daa503f000200000f | OK (8 keys, vim 13)  | OK (8 keys, vim 13)  |
| http://vimgolf.com/challenges/50d0d80eaa503f000200001b | OK (6 keys, vim 10)  | OK (6 keys, vim 10)  |
| http://vimgolf.com/challenges/50ee7504c0e3aa0002000040 | OK (16 keys, vim 17) | OK (18 keys, vim 17) |
| http://vimgolf.com/challenges/51103ad8041832000200003f | OK (27 keys, vim 20) | OK (29 keys, vim 20) |
| http://vimgolf.com/challenges/5192f96ad8df110002000002 | OK (13 keys, vim 13) | OK (13 keys, vim 13) |
| http://vimgolf.com/challenges/51f4a64c6813e30002000018 | OK (11 keys, vim 14) | OK (10 keys, vim 14) |
| http://vimgolf.com/challenges/521c805d860021000200007d | OK (10 keys, vim 12) | OK (10 keys, vim 12) |
| http://vimgolf.com/challenges/524e1a20b81fe50002000008 | OK (19 keys, vim 19) | OK (19 keys, vim 19) |
| http://vimgolf.com/challenges/52552abfb089a00002000007 | OK (18 keys, vim 23) | OK (18 keys, vim 23) |
| http://vimgolf.com/challenges/52c3cb0d9b8634000200000e | OK (14 keys, vim 11) | OK (14 keys, vim 11) |
| http://vimgolf.com/challenges/5325695c6092800002072d06 | OK (17 keys, vim 17) | OK (17 keys, vim 17) |
| http://vimgolf.com/challenges/53369b712a09c1000223fb57 | OK (30 keys, vim 25) | OK (30 keys, vim 25) |
| http://vimgolf.com/challenges/536cfa23fcccd100025678bd | OK (15 keys, vim 13) | OK (15 keys, vim 13) |
| http://vimgolf.com/challenges/537a553282aa3e000222048a | OK (23 keys, vim 33) | OK (23 keys, vim 33) |
| http://vimgolf.com/challenges/53c66c482b4166000226bbee | OK (8 keys, vim 11)  | OK (8 keys, vim 11)  |
| http://vimgolf.com/challenges/53d93fc3768e280002124f23 | OK (5 keys, vim 7)   | OK (5 keys, vim 7)   |
| http://vimgolf.com/challenges/53eb4ac3f690b50002f871b6 | OK (15 keys, vim 13) | OK (15 keys, vim 13) |
| http://vimgolf.com/challenges/540629666a1e4000020d9e5a | OK (9 keys, vim 13)  | OK (9 keys, vim 13)  |
| http://vimgolf.com/challenges/5421e49fdbded100021e4934 | OK (13 keys, vim 13) | OK (13 keys, vim 13) |
| http://vimgolf.com/challenges/54345d14d529ef0002227d4c | OK (11 keys, vim 9)  | OK (11 keys, vim 9)  |
| http://vimgolf.com/challenges/5447b459380e8b0002000db3 | OK (10 keys, vim 11) | OK (10 keys, vim 11) |
| http://vimgolf.com/challenges/54595b13128576000257a3c1 | OK (10 keys, vim 11) | OK (10 keys, vim 11) |
| http://vimgolf.com/challenges/5462e3f41198b80002512673 | OK (10 keys, vim 10) | OK (10 keys, vim 10) |
| http://vimgolf.com/challenges/54698da795f6da00020d85ed | OK (10 keys, vim 12) | OK (10 keys, vim 12) |
| http://vimgolf.com/challenges/54862fbb3f90ac0002904cf5 | OK (8 keys, vim 7)   | OK (8 keys, vim 7)   |
| http://vimgolf.com/challenges/54a8fb2ff4048c0002479f12 | OK (11 keys, vim 12) | OK (11 keys, vim 12) |
| http://vimgolf.com/challenges/54ddd1d261cec11d1b01707c | OK (9 keys, vim 9)   | OK (9 keys, vim 9)   |
| http://vimgolf.com/challenges/54df95a4a4b28331e9000003 | OK (14 keys, vim 15) | OK (14 keys, vim 15) |
| http://vimgolf.com/challenges/54f6e85d8dca0315e1010de1 | OK (28 keys, vim 21) | OK (24 keys, vim 21) |
| http://vimgolf.com/challenges/5518cd2bfb03aa1d9402a6a3 | OK (15 keys, vim 18) | OK (17 keys, vim 18) |
| http://vimgolf.com/challenges/5526aef5814f89118e00f23c | OK (13 keys, vim 15) | OK (13 keys, vim 15) |
| http://vimgolf.com/challenges/553b97364ba96c319d0296eb | OK (16 keys, vim 18) | OK (16 keys, vim 18) |
| http://vimgolf.com/challenges/55771cc4750ef86573003b83 | OK (10 keys, vim 17) | OK (10 keys, vim 17) |
| http://vimgolf.com/challenges/559c30948ef59c0eb7000002 | OK (9 keys, vim 12)  | OK (9 keys, vim 12)  |
| http://vimgolf.com/challenges/55b18bbea9c2c30d04000001 | OK (28 keys, vim 22) | OK (29 keys, vim 22) |
| http://vimgolf.com/challenges/55bcdc3ef4219f456102374f | OK (11 keys, vim 12) | OK (11 keys, vim 12) |
| http://vimgolf.com/challenges/55d7692d134b34420f05ac0b | OK (10 keys, vim 12) | OK (10 keys, vim 12) |
| http://vimgolf.com/challenges/55f9720b4a665c2acf0008c8 | OK (57 keys, vim 59) | OK (55 keys, vim 59) |
| http://vimgolf.com/challenges/55ff7ea45a2b52043e06dee2 | OK (20 keys, vim 32) | OK (20 keys, vim 32) |
| http://vimgolf.com/challenges/56421fb1603ec626ec000003 | OK (15 keys, vim 18) | OK (15 keys, vim 18) |
| http://vimgolf.com/challenges/56d70389bbbe462aff01d42a | OK (10 keys, vim 11) | OK (10 keys, vim 11) |
| http://vimgolf.com/challenges/56e69da07b3d84520a000001 | OK (16 keys, vim 14) | OK (18 keys, vim 14) |
| http://vimgolf.com/challenges/56fb2e75ccffcc0009026473 | OK (13 keys, vim 14) | OK (13 keys, vim 14) |
| http://vimgolf.com/challenges/571808767dd9d30009000001 | OK (7 keys, vim 11)  | OK (7 keys, vim 11)  |
| http://vimgolf.com/challenges/57343555fd77ad227900df4a | OK (14 keys, vim 15) | OK (14 keys, vim 15) |
| http://vimgolf.com/challenges/576c778ea4896a561b01b4f2 | OK (12 keys, vim 13) | OK (12 keys, vim 13) |
| http://vimgolf.com/challenges/57786c012ec4a10d2e000001 | OK (14 keys, vim 16) | OK (14 keys, vim 16) |
| http://vimgolf.com/challenges/57a208ce38e7e83a43000003 | OK (12 keys, vim 14) | OK (12 keys, vim 14) |
| http://vimgolf.com/challenges/57a87f444f1a8e3c4000ff8c | OK (7 keys, vim 15)  | OK (7 keys, vim 15)  |
| http://vimgolf.com/challenges/57cf3e398c660c1f8f014717 | OK (10 keys, vim 10) | OK (10 keys, vim 10) |
| http://vimgolf.com/challenges/57d7d06d9ce5640f6f000001 | OK (15 keys, vim 12) | OK (15 keys, vim 12) |
| http://vimgolf.com/challenges/5853f052854f48716101cc70 | OK (12 keys, vim 15) | OK (12 keys, vim 15) |
| http://vimgolf.com/challenges/58753af0f5ef5c0006000006 | OK (18 keys, vim 24) | OK (18 keys, vim 24) |
| http://vimgolf.com/challenges/587cab5a0740c90006000006 | OK (10 keys, vim 9)  | OK (10 keys, vim 9)  |
| http://vimgolf.com/challenges/587e0a9d5944680006000007 | OK (17 keys, vim 18) | OK (17 keys, vim 18) |
| http://vimgolf.com/challenges/58860440c57fb30006000004 | OK (33 keys, vim 34) | OK (33 keys, vim 34) |
| http://vimgolf.com/challenges/591903ff3060ed0b32000007 | OK (17 keys, vim 18) | OK (17 keys, vim 18) |
| http://vimgolf.com/challenges/59265921e633730ce0000016 | OK (10 keys, vim 9)  | OK (10 keys, vim 9)  |
| http://vimgolf.com/challenges/592e0f555b60ba0009000001 | OK (10 keys, vim 9)  | OK (10 keys, vim 9)  |
| http://vimgolf.com/challenges/59384eb3652ee111a0000001 | OK (14 keys, vim 17) | OK (16 keys, vim 17) |
| http://vimgolf.com/challenges/594ae5d6776ef706ab000009 | OK (8 keys, vim 8)   | OK (8 keys, vim 8)   |
| http://vimgolf.com/challenges/59553bd164628d0009000038 | OK (18 keys, vim 15) | OK (19 keys, vim 15) |
| http://vimgolf.com/challenges/5957c3356f7e17045b00002c | OK (24 keys, vim 23) | OK (24 keys, vim 23) |
| http://vimgolf.com/challenges/595cf3b0e9c7a8083500001b | OK (34 keys, vim 37) | OK (34 keys, vim 37) |
| http://vimgolf.com/challenges/596dd9ca448256000c000011 | OK (16 keys, vim 16) | OK (16 keys, vim 16) |
| http://vimgolf.com/challenges/59a2167bd6550c0006000005 | OK (14 keys, vim 19) | OK (14 keys, vim 19) |
| http://vimgolf.com/challenges/59a95b5a3e0a8d01da000004 | OK (14 keys, vim 15) | OK (14 keys, vim 15) |
| http://vimgolf.com/challenges/5a0c38cd2e62f404f000001b | OK (19 keys, vim 16) | OK (22 keys, vim 16) |
| http://vimgolf.com/challenges/5a33022f2de3f1021300000d | OK (21 keys, vim 23) | OK (21 keys, vim 23) |
| http://vimgolf.com/challenges/5abb80fc40f4d919b6000002 | OK (13 keys, vim 21) | OK (13 keys, vim 21) |
| http://vimgolf.com/challenges/5b0ba8a4dd701305aeb59201 | OK (36 keys, vim 9)  | OK (36 keys, vim 9)  |
| http://vimgolf.com/challenges/5b6e21c9a893790006232531 | OK (14 keys, vim 19) | OK (14 keys, vim 19) |
| http://vimgolf.com/challenges/5b6f0fcba89379000c2328a4 | OK (8 keys, vim 14)  | OK (8 keys, vim 14)  |
| http://vimgolf.com/challenges/5b71fa9105b5ca000ce4a7a1 | OK (25 keys, vim 29) | OK (25 keys, vim 29) |
| http://vimgolf.com/challenges/5b9131545c53aa000ca952f6 | OK (24 keys, vim 27) | OK (24 keys, vim 27) |
| http://vimgolf.com/challenges/5ba020f91abf2d000951055c | OK (14 keys, vim 12) | OK (14 keys, vim 12) |
| http://vimgolf.com/challenges/5ba4962fbbac05000bc2ddec | OK (29 keys, vim 30) | OK (29 keys, vim 30) |
| http://vimgolf.com/challenges/5bbb82f969a25f0009541350 | OK (10 keys, vim 12) | OK (10 keys, vim 12) |
| http://vimgolf.com/challenges/5bf26adb9a198b0009ce0a87 | OK (22 keys, vim 23) | OK (22 keys, vim 23) |
| http://vimgolf.com/challenges/5bff6e560d5dc0000ca3485b | OK (27 keys, vim 34) | OK (26 keys, vim 34) |
| http://vimgolf.com/challenges/5c26181de8c649000cfcac17 | OK (12 keys, vim 14) | OK (12 keys, vim 14) |
| http://vimgolf.com/challenges/5c264e64e8c64916d7fca650 | OK (9 keys, vim 9)   | OK (9 keys, vim 9)   |
| http://vimgolf.com/challenges/5c4d042acfafb4000c9f06c2 | OK (9 keys, vim 12)  | OK (9 keys, vim 12)  |
| http://vimgolf.com/challenges/5c52df3ff6983b0006c69e80 | OK (19 keys, vim 19) | OK (19 keys, vim 19) |
| http://vimgolf.com/challenges/5c5f20c1e2dcab0009c10530 | OK (26 keys, vim 22) | OK (26 keys, vim 22) |
| http://vimgolf.com/challenges/5c742a5a50bdf70006d43280 | OK (24 keys, vim 21) | OK (24 keys, vim 21) |
| http://vimgolf.com/challenges/5c75b4246c2f8300092b8d97 | OK (63 keys, vim 40) | OK (63 keys, vim 40) |
| http://vimgolf.com/challenges/5c82a157c82f3900064c82d7 | OK (14 keys, vim 15) | OK (14 keys, vim 15) |
| http://vimgolf.com/challenges/5c93945c9caf21000ca842f7 | OK (20 keys, vim 17) | OK (20 keys, vim 17) |
| http://vimgolf.com/challenges/5cb9d07d716c1b0009f69a40 | OK (13 keys, vim 14) | OK (13 keys, vim 14) |
| http://vimgolf.com/challenges/5cc31feaffd607000ccf6ea7 | OK (42 keys, vim 48) | OK (42 keys, vim 48) |
| http://vimgolf.com/challenges/5d01c60354ee2200067df987 | OK (12 keys, vim 16) | OK (12 keys, vim 16) |
| http://vimgolf.com/challenges/5d745e799a72d600095eb7af | OK (34 keys, vim 38) | OK (34 keys, vim 38) |
| http://vimgolf.com/challenges/5e3c8d176ea90a00096b2e63 | OK (18 keys, vim 21) | OK (18 keys, vim 21) |
| http://vimgolf.com/challenges/9v00619554dd000000000216 | OK (11 keys, vim 10) | OK (11 keys, vim 10) |

### CODE REVIEW

**Comment by mawww** [comment]
Thanks for working on that :)

**Comment by arrufat** [comment]
It may take some time, though

**Comment by arrufat** [comment]
Done!

**Comment by arrufat** [comment]
Hi @mawww, this is just a gentle reminder that this PR is ready :)

**Comment by arrufat** [comment]
Hi @mawww, could you have a look when you have time :)

**Comment by mawww** [comment]
Thanks !

**Pull request merged**
